In [3]:
import pandas as pd
import requests
from config import API_KEY

In [6]:
response=requests.get(f'https://api.themoviedb.org/3/movie/popular?api_key={API_KEY}')

In [10]:
df=pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]

In [11]:
df.head()

,id,title,overview,release_date,popularity,vote_average,vote_count
0,969681,Spider-Man: Brand New Day,Fighting crime full-time as Spider-Man in a wo...,2026-07-29,1227.7402,8.469,5977
1,687163,Project Hail Mary,Science teacher Ryland Grace wakes up on a spa...,2026-03-15,1019.0916,8.635,8446
2,1003596,Avengers: Doomsday,Beloved heroes from three distinct universes a...,2026-12-16,764.9682,0.000,0
3,1058424,Hope,In the remote South Korean village of Hope Har...,2026-07-15,458.5083,6.900,298
4,1368337,The Odyssey,"Odysseus, the legendary King of Ithaca, embark...",2026-07-15,423.1889,8.015,4221

In [18]:
df=pd.DataFrame()
df_list=[]

In [19]:
df

Empty DataFrame
Columns: []
Index: []

In [ ]:
for i in range(1,1002):
    response=requests.get(f'https://api.themoviedb.org/3/movie/popular?api_key={API_KEY}&page{i}')
    temp_df=pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]
    df_list.append(temp_df)
    
df=pd.concat(df_list,ignore_index=True)

In [21]:
df

,id,title,overview,release_date,popularity,vote_average,vote_count
0,969681,Spider-Man: Brand New Day,Fighting crime full-time as Spider-Man in a wo...,2026-07-29,1227.7402,8.469,5977
1,687163,Project Hail Mary,Science teacher Ryland Grace wakes up on a spa...,2026-03-15,1019.0916,8.635,8446
2,1003596,Avengers: Doomsday,Beloved heroes from three distinct universes a...,2026-12-16,764.9682,0.000,0
3,1058424,Hope,In the remote South Korean village of Hope Har...,2026-07-15,458.5083,6.900,298
4,1368337,The Odyssey,"Odysseus, the legendary King of Ithaca, embark...",2026-07-15,423.1889,8.015,4221
...,...,...,...,...,...,...,...
17835,1423191,Resident Evil,Medical courier Bryan unwittingly finds himsel...,2026-09-16,168.7962,7.297,1031
17836,1377237,Runner,A former soldier is thrown into a brutal race ...,2026-09-07,147.3325,8.335,694
17837,1514026,Buddy,"A magical, singing orange unicorn holds his ca...",2026-08-27,159.0998,7.118,165
17838,1712451,Resident Dead,A man keeping his recently zombified daughter ...,2026-09-04,146.4247,6.042,12
17839,1284186,Sacrifice,During a star-studded charity gala brimming wi...,2026-04-09,140.3962,5.143,63

In [22]:
df.to_csv('movies.csv')